services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      
    networks:
      - lmsbackend_my_network
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - lmsbackend_my_network
    ports:
      - "8080:80"

  web:
    build: .
    image: lmslatest
    command: daphne -b 0.0.0.0 -p 8888 lms_project.asgi:application
    volumes:
      - ./:/code
      - ./media:/code/media
      - ./static:/code/static
      - ./templates:/code/templates
    working_dir: /code
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db  # Use service name 'db' here, NOT localhost
      - POSTGRES_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - lmsbackend_my_network

networks:
  lmsbackend_my_network:
    driver: bridge